image: maven:latest
stages:
  - build
  - test
  - deploy
build_1:
  stage: build
  tags:
    - perli-runner1
  script:
    - mvn compile
test:
  stage: test
  tags:
    - perli-runner1
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.war
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
deploy:
  stage: deploy
  tags:
    - perli-runner1
  when: manual
  allow_failure: false
  script:
    - echo 'Deploy'
